{"metadata": {"timestamp": "2024-04-17T23:07:28.685168+00:00", "tools": [{"externalReferences": [{"type": "build-system", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/actions"}, {"type": "distribution", "url": "https://pypi.org/project/cyclonedx-python-lib/"}, {"type": "documentation", "url": "https://cyclonedx.github.io/cyclonedx-python-lib/"}, {"type": "issue-tracker", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/issues"}, {"type": "license", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/LICENSE"}, {"type": "release-notes", "url": "https://github.com/CycloneDX/cyclonedx-python-lib/blob/main/CHANGELOG.md"}, {"type": "vcs", "url": "https://github.com/CycloneDX/cyclonedx-python-lib"}, {"type": "website", "url": "https://cyclonedx.org"}], "name": "cyclonedx-python-lib", "vendor": "CycloneDX", "version": "4.0.0"}, {"externalReferences": [{"type": "build-system", "url": "https://github.com/madpah/vexy/actions"}, {"type": "distribution", "url": "https://pypi.org/project/vexy/"}, {"type": "documentation", "url": "https://vexy.readthedocs.io/"}, {"type": "issue-tracker", "url": "https://github.com/madpah/vexy/issues"}, {"type": "license", "url": "https://github.com/madpah/vexy/blob/main/LICENSE"}, {"type": "release-notes", "url": "https://github.com/madpah/vexy/blob/main/CHANGELOG.md"}, {"type": "vcs", "url": "https://github.com/madpah/vexy"}], "name": "vexy", "vendor": "Vexy", "version": "0.3.1"}]}, "serialNumber": "urn:uuid:4e058aa7-1ef5-4bd2-a2c0-be6533995c83", "version": 1, "vulnerabilities": [{"advisories": [{"url": "http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2024-27281"}, {"url": "https://github.com/advisories/GHSA-592j-995h-p23j"}], "affects": [{"ref": "urn:cdx:abe3a106-fc7f-4097-8069-75fac2588d17/1#pkg:gem/rdoc@6.6.2", "versions": [{"status": "unknown", "version": "6.6.2"}]}], "bom-ref": "0f9522dc-f628-4b9d-8661-19991945accd", "cwes": [502], "description": "[CVE-2024-27281] CWE-502: Deserialization of Untrusted Data", "detail": "rdoc - Deserialization of Untrusted Data\n\nSonatype's research suggests that this CVE's details differ from those defined at NVD. See https://ossindex.sonatype.org/vulnerability/CVE-2024-27281 for details", "ratings": [{"method": "CVSSv3", "score": 8.8, "severity": "high", "source": {"name": "OSS Index by Sonatype", "url": "https://ossindex.sonatype.org/vulnerability/CVE-2024-27281?component-type=gem&component-name=rdoc&utm_source=python-oss-index-lib%401.1.1&utm_medium=integration"}, "vector": "AV:N/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"}], "references": [{"id": "CVE-2024-27281", "source": {"name": "OSS Index by Sonatype", "url": "https://ossindex.sonatype.org/vulnerability/CVE-2024-27281?component-type=gem&component-name=rdoc&utm_source=python-oss-index-lib%401.1.1&utm_medium=integration"}}], "source": {"name": "OSS Index by Sonatype", "url": "https://ossindex.sonatype.org/"}}], "$schema": "http://cyclonedx.org/schema/bom-1.4.schema.json", "bomFormat": "CycloneDX", "specVersion": "1.4"}